# Generated by Django 5.0.2 on 2024-03-02 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_relation_database'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatabaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_at', models.DateTimeField(verbose_name='Дата и время окончания сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания сессии')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.database', verbose_name='База данных')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия БД пользователя',
                'verbose_name_plural': 'Сессии БД пользователей',
            },
        ),
    ]
