# Generated by Django 5.0.2 on 2024-03-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_userdatabasesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabasesession',
            name='operations_count',
            field=models.IntegerField(default=0, verbose_name='Количество операций'),
        ),
    ]
