# Generated by Django 5.0.6 on 2024-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0006_alter_database_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="position",
            field=models.JSONField(null=True, verbose_name="Координаты на плоскости"),
        ),
    ]
