# Generated by Django 5.0.6 on 2024-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_inviter"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, null=True, verbose_name="Email"),
        ),
    ]
