# Generated by Django 5.0.2 on 2024-04-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_usertask_created_at_usertask_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='updated_at',
            field=models.DateField(null=True, verbose_name='Дата и время обновления'),
        ),
    ]
